export const questions = [
  "How do I feel today, and why?",
  "What is one thing I’m grateful for today?",
  "What challenged me today?",
  "What made me smile today?",
  "Did I take a step toward my goals today?",
  "What did I learn about myself today?",
  "What’s something I wish I handled differently?",
  "What am I avoiding and why?",
  "How did I care for myself today?",
  "What was the best moment of the day?",
  "What drained my energy today?",
  "Who or what inspired me today?",
  "What is one thing I could do better tomorrow?",
  "What did I say ‘yes’ to that I should have said ‘no’?",
  "What’s one small win I achieved today?",
  "What do I need to forgive myself for?",
  "How did I react under stress today?",
  "What am I currently excited about?",
  "What emotions did I feel most strongly today?",
  "Did I spend my time wisely today?",
  "What habits are helping me right now?",
  "What habits are holding me back?",
  "How did I connect with others today?",
  "What thoughts kept repeating in my mind today?",
  "What does my body need right now?",
  "What am I proud of myself for today?",
  "How did I show kindness today?",
  "What do I need to let go of?",
  "If today had a theme, what would it be?",
  "What story am I telling myself right now?",
]
